### ISSUE TITLE
Incorrect color conversion from Hex to HSLa and back

### ISSUE THREAD

**Issue by onlineth** [metaloha/color2color#10]
Hi, using color2color, the Hex, #f45ef4 converted to HLSa returns as hsla(300,86%,66%,1) and back to Hex goes back to #f45ef4. This, however, is not true as if you input the hsla format [here](http://www.w3schools.com/colors/colors_hsl.asp), it gives a Hex of #f35ef3. Is this an issue with the actual format or the script? (Is it not possible for any HSLa format to equal #f45ef4?)

**Comment by metaloha** [comment]
I'll look into this - it may be a rounding error in the code.

**Comment by onlineth** [comment]
Ok, thanks:)

**Comment by metaloha** [comment]
There are indeed multiple Hex values that map to some HSL combinations.

In this specific case, my code "correctly" rounds the saturation value from 86.2% to 86%. Every other converter I've checked seems to  move to the next higher integer instead, so I wonder if that's actually the correct method. I'm not making the patch until I know for sure, so if you know of an authoritative source for the math involved, now's the time to let me know :)

**Comment by metaloha** [comment]
I think I've patched this now. The new tests take the "drift" into account (eg.`#ddffee` converted to `hsl(150,100%,93%)` will actually become `#dbffed`). This is normal, since HSL (and HSV/HSB) have a smaller colourspace than RGB. Any RGB values that perfectly convert to HSL and back are coincidences, and different developers might be rounding things differently (I use `Math.round`, but I've seen `parseInt`, `ceil` and `floor` all being used as well).
